/// @description Init

display_set_gui_size(256,144);
global.controller = 0;
global.paused = false;
global.hitStop = false;
global.canPause = false;
global.coins = 0;
global.maxHealth = 6;
global.health = 6;
global.infiniteHealth = false;
global.item = -1;
global.itemSprites = [sKunaiUI,sBootsUI,sShockUI,sCritUI,sGobletUI,sColaUI,sHeart];
global.itemObjects = [oKunaiItem,oBootsItem,oShockItem,oCritItem,oGobletItem,oColaItem,oHeart];
global.passiveItems = [];
global.passiveItemSprites = [sShockUI,sCritUI,sGobletUI,sColaUI];
global.sword = true;
global.tutorialCompleted = false;
global.runCompleted = false;
global.inARun = false;
global.sideRoomArray = [rTreasureRoom,rTreasureRoom2];
global.levelArray = [rFloor1_1,rRunTest2,rRunTest6];
global.usedArray = [false,false,false,false,false];
global.levelCount = 0;
global.pipeCount = 0;
global.originalRoom = room;
global.sideRoom = rTitle;
global.sideChestOpened = false;
global.pipeSpawned = false;
global.pipeY = 0;
global.gobletCombo = 0;
global.gobletVFX = [o1,o2,o3,o4,o5,oHealthGetVFX];
menuOption = 0;
analogUpPrev = false;
analogDownPrev = false;
analogUpPrevD = false;
analogDownPrevD = false;
coinTextScale = 1;
healthTextScale = 1;
itemTextScale = 1;
passiveItemTextScale = 1;
options = false;
deleted = false;

Load();